#!/usr/bin/env python3
"""Single source of truth for the readiness/capability PROSE embedded in STATUS.md, README.md,
and KNOWN-LIMITATIONS.md.

`benchmarks/capabilities.json` is the sole authority for capability STATE (audit.py's R9
dimension reads it too). This script machine-owns ONLY the text between matched
`<!-- CAPABILITY-STATUS:<ID>:BEGIN -->` / `<!-- CAPABILITY-STATUS:<ID>:END -->` marker pairs in a
small registered set of files — it never touches hand-written physics prose outside those markers.

% source (avoids chicken-and-egg with a possibly-stale committed AUDIT.md): every builder computes
the headline straight from `audit.CHECKS` (imported live from scripts/audit.py, same directory) —
`rows = [f() for f in audit.CHECKS]; readiness = round(100*sum(r[2] for r in rows)/len(rows))` — and
the per-prompt board + capabilities straight from `benchmarks/capabilities.json`. This script
never reads the committed AUDIT.md for a number, so gen_status.py and `python scripts/audit.py`
can never disagree — both are pure functions of the same live CHECKS + matrix.

Marker scheme (HTML comments, invisible in rendered markdown; no sha, no timestamp — content is
the only thing that can drift):

    <!-- CAPABILITY-STATUS:<ID>:BEGIN (auto-generated by scripts/gen_status.py from
         benchmarks/capabilities.json — DO NOT EDIT inside these markers) -->
    <generated body>
    <!-- CAPABILITY-STATUS:<ID>:END -->

Modes:
    --check     (default) rebuild every registered block in memory, diff against what is on disk
                for every registered file, print the diff, exit 1 on ANY drift.
    --write     splice the freshly-built body between each block's marker pair in every registered
                file. FAILS LOUD (nonzero exit, no partial write) if a registered file lacks the
                marker pair for a block it is supposed to carry — it never silently skips a file.
    --selftest  build every block from the live matrix, prove it is round-trip stable (write into a
                temp copy of each registered file, re-derive fresh, expect zero diff against the
                temp copy), and assert the served/partial/unbuilt counts equal the matrix.

Insert EMPTY marker pairs (BEGIN comment immediately followed by END comment, no body) at the
places the blocks belong, then run `gen_status.py --write` to populate them.
"""
import argparse
import difflib
import json
import os
import re
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# `import audit` == same-directory scripts/audit.py (the % source of truth; see module docstring).
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import audit  # noqa: E402  (scripts/audit.py)


def p(*a):
    return os.path.join(ROOT, *a)


def rel(path):
    return os.path.relpath(path, ROOT)


MATRIX_PATH = p("benchmarks", "capabilities.json")


def load_matrix():
    with open(MATRIX_PATH, encoding="utf-8") as f:
        return json.load(f)


# Ordered P1..P7 labels, independent of capability-matrix.json's own dict insertion order (kept
# explicit so a re-ordering of the JSON can't silently re-letter the board).
PROMPT_LABELS = [
    ("P1_hvt_zprime_ww_summary", "P1"),
    ("P2_toponium_heavy_higgs_summary", "P2"),
    ("P3_svj_expansion_tagger", "P3"),
    ("P4_dijet_photon_widths", "P4"),
    ("P5_cms_abc_dijet", "P5"),
    ("P6_atlas_model_agnostic_ad", "P6"),
    ("P7_displaced_run3_replane", "P7"),
]

# capability-code -> short human hint, used only to decorate which engine served a prompt in the
# HEADLINE paragraph. Purely cosmetic; the served/partial/unbuilt COUNTS never depend on this.
_CAP_HINT = {
    "G1_summary_track": "summary track",
    "G2a_effmap_folding": "efficiency-map fold",
    "G2b_shape_fit_engine_OR_refusal": "shape-fit engine",
    "G2c_projection": "projection",
    "G2d_replane": "replane",
    "G3_generator_config_gates": "generator-config gates",
    "G4_basis_manifest": "basis manifest",
    "G5_trap_sweep": "trap sweep",
    "G6_ladder": "ladder",
}

FULL_STATUSES = ("served", "served-with-refusal")
PARTIAL_STATUSES = ("partial",)
UNBUILT_STATUSES = ("unbuilt", "decision-pending")


def _readiness_and_r9():
    """Pure function of the LIVE audit.CHECKS — never reads the committed AUDIT.md."""
    rows = [f() for f in audit.CHECKS]
    readiness = round(100 * sum(r[2] for r in rows) / len(rows))
    r9 = next((r for r in rows if r[0] == "R9"), None)
    if r9 is None:
        raise SystemExit("gen_status: audit.CHECKS carries no R9 row — audit.py has drifted")
    return readiness, r9[2], r9[3]  # readiness %, R9 score (0..1), R9 status (PASS/WARN/FAIL)


def _board(matrix):
    """label -> (key, status) for every P1..P7, in canonical order. Fails loud if
    capability-matrix.json and PROMPT_LABELS have drifted apart (missing/extra prompt keys)."""
    prompts = matrix.get("prompts", {})
    board = []
    for key, label in PROMPT_LABELS:
        if key not in prompts:
            raise SystemExit(f"gen_status: capability-matrix.json is missing prompt key {key!r} "
                              f"(PROMPT_LABELS expects it as {label}) — matrix and generator have "
                              f"drifted; update PROMPT_LABELS in scripts/gen_status.py")
        board.append((label, key, prompts[key]))
    extra = set(prompts) - {k for k, _ in PROMPT_LABELS}
    if extra:
        raise SystemExit(f"gen_status: capability-matrix.json has prompt key(s) not in "
                          f"PROMPT_LABELS: {sorted(extra)} — update scripts/gen_status.py")
    return board


def _bucket(board, statuses):
    return [label for label, _key, v in board if v.get("status") in statuses]


# ---------------------------------------------------------------------------
# Block builders — each is a pure function of audit.CHECKS + capability-matrix.json.
# ---------------------------------------------------------------------------

def build_headline():
    readiness, r9_score, r9_status = _readiness_and_r9()
    matrix = load_matrix()
    board = _board(matrix)
    prompts = matrix["prompts"]
    total = len(board)

    full = _bucket(board, FULL_STATUSES)
    refusal = _bucket(board, ("served-with-refusal",))
    partial = _bucket(board, PARTIAL_STATUSES)
    unbuilt = _bucket(board, UNBUILT_STATUSES)

    def hinted(label):
        key = next(k for k, l in PROMPT_LABELS if l == label)
        for req in prompts[key].get("requires", []):
            if req in _CAP_HINT:
                return f"{label} {_CAP_HINT[req]}"
        return label

    full_desc = ", ".join(hinted(l) for l in full) if full else "none yet"
    partial_desc = ", ".join(partial) if partial else "none"
    unbuilt_desc = (" (" + ", ".join(unbuilt) + ")") if unbuilt else ""

    return (
        f"**Reference-task coverage {r9_score:.2f} ({r9_status})** on the "
        f"project's benchmark of {total} reference physicist tasks — real requests collected from "
        f"CERN researchers, used as the standing coverage yardstick (internal audit dimension "
        f"\"R9\"). **{len(full)} of {total} fully served** ({full_desc}; {len(refusal)} served by "
        f"a designed refusal), **{len(partial)} partially served** ({partial_desc}), "
        f"**{len(unbuilt)} not yet built**{unbuilt_desc}. Task list, scoring, and definitions: "
        f"`benchmarks/capabilities.json` → `docs/development/audit.md`. "
        f"These are internal coverage categories, not measured autonomous success rates or "
        f"a percentage of scientific correctness. The live audit inventory score depends on "
        f"which development artifacts are installed."
    )


def build_board():
    matrix = load_matrix()
    board = _board(matrix)
    lines = ["| Prompt | task_mode | Status | Residual |", "|---|---|---|---|"]
    for label, _key, v in board:
        blocking = v.get("blocking") or []
        residual = blocking[0] if blocking else "—"
        lines.append(f"| {label} | {v.get('task_mode', '?')} | {v.get('status', '?')} | {residual} |")
    return "\n".join(lines)


def build_capabilities():
    matrix = load_matrix()
    caps = matrix.get("capabilities", {})
    lines = ["| Capability | Status |", "|---|---|"]
    for code, v in caps.items():
        lines.append(f"| {code} | {v.get('status', '?')} |")
    return "\n".join(lines)


def build_shapefit():
    matrix = load_matrix()
    g2b_status = matrix["capabilities"]["G2b_shape_fit"]["status"]
    p4_status = matrix["prompts"]["P4_dijet_photon_widths"]["status"]
    # "8/20 (~40%)" is the fixed pre-registered census constant (framework/interrogations/
    # generality.md) — it is a one-time measured fact of the census population, not derived from
    # the live matrix, so it is hardcoded here rather than computed.
    return (
        "~40% of the search population (8/20, pre-registered census) is shape/template-fit; "
        "these route to the scoped `shape_fit.py` engine (`stat_mode=shape-fit`), R5-gated per "
        "analysis. Only an unrepresentable fit (unbinned / multi-observable / per-event NN) "
        "downgrades to the named `blocked-shape-fit` refusal + generator-level offer "
        f"(PRODUCT-CONTRACT §6.1). Matrix: P4 {p4_status}, G2b {g2b_status}."
    )


# ---------------------------------------------------------------------------
# Block -> file registry
# ---------------------------------------------------------------------------

BLOCKS = {
    "HEADLINE": (build_headline, [p("docs", "development", "status.md"), p("docs", "reference", "capabilities.md")]),
    "BOARD": (build_board, [p("docs", "development", "status.md")]),
    "CAPABILITIES": (build_capabilities, [p("docs", "development", "status.md")]),
    "SHAPEFIT": (build_shapefit, [p("docs", "reference", "capabilities.md"), p("docs", "reference", "limitations.md")]),
}


def _marker_pattern(block_id):
    bid = re.escape(block_id)
    return re.compile(
        r"(<!-- CAPABILITY-STATUS:%s:BEGIN.*?-->\n)(.*?)(<!-- CAPABILITY-STATUS:%s:END -->)" % (bid, bid),
        re.DOTALL,
    )


def _current_block(path, block_id):
    """Returns (current_body_or_None, full_text). None means the marker pair is absent."""
    text = open(path, encoding="utf-8").read()
    m = _marker_pattern(block_id).search(text)
    if not m:
        return None, text
    return m.group(2), text


def _splice(text, block_id, body):
    """Returns new_text with the block_id's body replaced by `body` (normalized to end in \\n)."""
    pat = _marker_pattern(block_id)
    m = pat.search(text)
    if not m:
        return None
    new_body = body.rstrip("\n") + "\n"
    return text[: m.start(2)] + new_body + text[m.end(2):]


# ---------------------------------------------------------------------------
# Modes
# ---------------------------------------------------------------------------

def cmd_write():
    missing = []
    bodies = {}
    for block_id, (builder, files) in BLOCKS.items():
        bodies[block_id] = builder()
        for path in files:
            if not os.path.exists(path):
                missing.append(f"{rel(path)}: file does not exist")
                continue
            _, text = _current_block(path, block_id)
            if _marker_pattern(block_id).search(text) is None:
                missing.append(f"{rel(path)}: missing CAPABILITY-STATUS:{block_id} marker pair "
                                f"— insert the empty markers first, then re-run --write")
    if missing:
        sys.stderr.write("gen_status --write: FAIL — marker pair(s) missing, wrote nothing:\n")
        for m in missing:
            sys.stderr.write(f"  - {m}\n")
        return 2

    changed = []
    for block_id, (builder, files) in BLOCKS.items():
        body = bodies[block_id]
        for path in files:
            text = open(path, encoding="utf-8").read()
            new_text = _splice(text, block_id, body)
            if new_text is None:
                # already validated present above; defensive only
                raise SystemExit(f"gen_status --write: marker pair for {block_id} vanished mid-run "
                                  f"in {rel(path)}")
            if new_text != text:
                open(path, "w", encoding="utf-8").write(new_text)
                changed.append(f"{rel(path)}:{block_id}")

    if changed:
        print(f"gen_status --write: wrote {len(changed)} block(s): {', '.join(changed)}")
    else:
        print("gen_status --write: no changes (every block already fresh)")
    return 0


def cmd_check():
    drift = []
    for block_id, (builder, files) in BLOCKS.items():
        fresh = builder().rstrip("\n") + "\n"
        for path in files:
            if not os.path.exists(path):
                drift.append(f"--- {rel(path)} ({block_id}): file does not exist ---")
                continue
            current, _text = _current_block(path, block_id)
            if current is None:
                drift.append(f"--- {rel(path)} ({block_id}): marker pair missing on disk ---")
                continue
            if current.strip("\n") != fresh.strip("\n"):
                diff = difflib.unified_diff(
                    current.splitlines(keepends=True),
                    fresh.splitlines(keepends=True),
                    fromfile=f"{rel(path)} ({block_id}) on disk",
                    tofile=f"{rel(path)} ({block_id}) fresh",
                )
                drift.append("".join(diff))
    if drift:
        print("gen_status --check: DRIFT detected\n")
        for d in drift:
            print(d)
        return 1
    print("gen_status --check: OK (all blocks fresh)")
    return 0


def cmd_selftest():
    problems = []
    tmpdir = tempfile.mkdtemp(prefix="gen_status_selftest_")
    try:
        # 1. round-trip stability: copy every registered file, write the live blocks into the
        #    copies, then re-derive fresh and confirm zero diff against the just-written copy.
        tmp_paths = {}
        all_paths = {path for _b, (_f, files) in BLOCKS.items() for path in files}
        for path in all_paths:
            tmp_path = os.path.join(tmpdir, os.path.basename(path))
            if not os.path.exists(path):
                problems.append(f"selftest: {rel(path)} does not exist — cannot round-trip")
                continue
            shutil.copy(path, tmp_path)
            tmp_paths[path] = tmp_path
            if _marker_pattern(next(iter(BLOCKS))).search(open(path, encoding="utf-8").read()) is None:
                pass  # not every file carries every block; per-block check below is authoritative

        for block_id, (builder, files) in BLOCKS.items():
            body = builder()
            for path in files:
                if path not in tmp_paths:
                    continue
                text = open(tmp_paths[path], encoding="utf-8").read()
                new_text = _splice(text, block_id, body)
                if new_text is None:
                    problems.append(f"selftest: {rel(path)} has no CAPABILITY-STATUS:{block_id} "
                                     f"marker pair — insert it before --selftest can validate it")
                    continue
                open(tmp_paths[path], "w", encoding="utf-8").write(new_text)

        for block_id, (builder, files) in BLOCKS.items():
            fresh = builder()
            for path in files:
                if path not in tmp_paths:
                    continue
                current, _ = _current_block(tmp_paths[path], block_id)
                if current is None:
                    continue  # already reported above
                if current.strip("\n") != fresh.strip("\n"):
                    problems.append(f"selftest: {block_id} in {rel(path)} is NOT round-trip stable")
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    # 2. counts equal the matrix
    matrix = load_matrix()
    board = _board(matrix)
    prompts = matrix["prompts"]
    served_n = len(_bucket(board, FULL_STATUSES))
    partial_n = len(_bucket(board, PARTIAL_STATUSES))
    unbuilt_n = len(_bucket(board, UNBUILT_STATUSES))
    exp_served = sum(1 for v in prompts.values() if v.get("status") in FULL_STATUSES)
    exp_partial = sum(1 for v in prompts.values() if v.get("status") in PARTIAL_STATUSES)
    exp_unbuilt = sum(1 for v in prompts.values() if v.get("status") in UNBUILT_STATUSES)
    if (served_n, partial_n, unbuilt_n) != (exp_served, exp_partial, exp_unbuilt):
        problems.append(
            f"selftest: board counts computed by gen_status ({served_n}/{partial_n}/{unbuilt_n}) "
            f"!= matrix counts ({exp_served}/{exp_partial}/{exp_unbuilt})")
    if served_n + partial_n + unbuilt_n != len(prompts):
        problems.append("selftest: served+partial+unbuilt does not cover every matrix prompt "
                         "(an unrecognized status value slipped through)")

    if problems:
        print("gen_status --selftest: FAIL")
        for pr in problems:
            print(f"  - {pr}")
        return 1
    print(f"gen_status --selftest: OK (round-trip stable; board {exp_served} served / "
          f"{exp_partial} partial / {exp_unbuilt} unbuilt of {len(prompts)})")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="splice fresh bodies into registered files")
    mode.add_argument("--check", action="store_true", help="diff on-disk blocks vs fresh (default)")
    mode.add_argument("--selftest", action="store_true", help="round-trip + count self-check")
    args = ap.parse_args()

    if args.write:
        sys.exit(cmd_write())
    elif args.selftest:
        sys.exit(cmd_selftest())
    else:
        sys.exit(cmd_check())


if __name__ == "__main__":
    main()
